// tslint:disable
/**
 * Submissions
 * This API specifies the submissions service, as accessed by the web admin UI used by students, lecturers and tutors. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The ability to read all submissions of a certain tutorial.
 * @export
 * @interface Tutor
 */
export interface Tutor  {
    /**
     * The user ID of the tutor. (foreign)
     * @type {number}
     * @memberof Tutor
     */
    userID?: number;
    /**
     * The ID of the tutor
     * @type {string}
     * @memberof Tutor
     */
    tutorialID?: string;
}

export function TutorFromJSON(json: any): Tutor {
    return {
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
        'tutorialID': !exists(json, 'tutorialID') ? undefined : json['tutorialID'],
    };
}

export function TutorToJSON(value?: Tutor): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'userID': value.userID,
        'tutorialID': value.tutorialID,
    };
}


